rewrite .gitmessage
Rduanchen/PTWASpecialEducation pull request #4
Opened 2024-09-05 08:57 UTC by 2min0623

2024-09-08 09:43 UTC, Rduanchen requested changes
To-do list:
1. Please change finditemgamev2 to another name
2. We will use the "Read the number" Function in another game, please move the reading number function to a separately library.


In addition to the items mentioned above, the others codes are OK!

2024-09-08 09:43 UTC, Rduanchen commented on src/views/GameTemplate/FindTheItemGameV2.vue
To-do list
1. Component請換一個名字

2024-09-08 09:43 UTC, Rduanchen commented on src/views/GameTemplate/FindTheItemGameV2.vue
> +  import { GamesGetAssetsFile } from '@/utilitys/get_assets.js';
Please use new API: gamesGetAssetFile.

2024-09-08 09:43 UTC, Rduanchen commented on src/views/GameTemplate/FindTheItemGameV2.vue
> +        numSound.src = GamesGetAssetsFile(this.id,`${number}.mp3`);
Use new API

2024-09-08 09:43 UTC, Rduanchen commented on src/views/GameTemplate/FindTheItemGameV2.vue
> +        numSound.src = GamesGetAssetsFile(this.id,`${number}.mp3`);
If you move the read number function to separately library, you have to use another API (you will have to change the audio files to another folder).

2024-09-08 11:02 UTC, 2min0623 commented on src/views/GameTemplate/FindTheItemGameV2.vue
> +        numSound.src = GamesGetAssetsFile(this.id,`${number}.mp3`);
原本那天你是請我把音檔放在assets/System/number
但getSystemEffectAssets這個是直接導到System/Effects這個資料夾
所以我才把音檔放到assets/Games/Dev0301裡做測試

如果我現在要修改的話我應該怎麼改?

2024-09-09 01:49 UTC, Rduanchen commented on src/views/GameTemplate/FindTheItemGameV2.vue
> +        numSound.src = GamesGetAssetsFile(this.id,`${number}.mp3`);
這的確是一個問題，解決方法是在 `get-asset.js` 底下新增一個這樣的函數

```
export function getSystemEffectAssets(url, service) {
   return new URL(`../assets/System/${service}/${url}`, import.meta.url).href
}
```

並且在 `@src/assets/System/` 底下新增一個資料夾叫做 `read-number` 來存放音檔

2024-09-09 02:05 UTC, Rduanchen commented
我剛剛看了一下遊戲的效果，整體來說很不錯了，但有幾點想要修正

1. 切換到下一關的時候自己撥放數字音效
2. 妳目前是以題目給的Range 做計算，但因為我們的特教生手指沒那麼精細，看看可不可以加上一個寬容值
3. 目前這個在ipad air 上面的效果是下面這張圖，我們主要的對象都是使用ipad，請修正RWD
![image](https://github.com/user-attachments/assets/167677dd-f890-4a79-a91e-62016aed3522)


感謝~

2024-09-10 05:14 UTC, Rduanchen approved these changes
收到了，謝謝

2024-09-10 05:15 UTC, merged